DROP TABLE IF EXISTS used_cars;
CREATE TABLE used_cars(
	vin TEXT,
	back_legroom TEXT,
	bed TEXT,
	bed_height TEXT,
	bed_length TEXT,
	body_type TEXT,
	cabin TEXT,
	city TEXT,
	city_fuel_economy NUMERIC,
	combine_fuel_economy NUMERIC,
	daysonmarket NUMERIC,
	dealer_zip TEXT,
	description TEXT,
	engine_cylinders TEXT,
	engine_displacement NUMERIC,
	engine_type TEXT,
	exterior_color TEXT,
	fleet BOOLEAN,
	frame_damaged BOOLEAN,
	franchise_dealer BOOLEAN,
	franchise_make TEXT,
	front_legroom TEXT,
	fuel_tank_volume TEXT,
	fuel_type TEXT,
	has_accidents BOOLEAN,
	height TEXT,
	highway_fuel_economy NUMERIC,
	horsepower NUMERIC,
	interior_color TEXT,
	isCab BOOLEAN,
	is_certified BOOLEAN,
	is_cpo BOOLEAN,
	is_new BOOLEAN,
	is_oemcpo BOOLEAN, 
	latitude NUMERIC,
	length TEXT,
	listed_date TEXT,
	listing_color TEXT,
	listing_id NUMERIC, 
	longitude NUMERIC, 
	main_picture_url TEXT, 
	major_options TEXT,
	make_name TEXT, 
	maximum_seating TEXT,
	mileage TEXT, 
	model_name TEXT,
	owner_count NUMERIC,
	power TEXT,
	price TEXT,
	salvage BOOLEAN,
	savings_amount NUMERIC,
	seller_rating NUMERIC,
	sp_id TEXT,
	sp_name TEXT, 
	theft_title BOOLEAN,
	torque TEXT,
	transmission TEXT,
	transmission_display TEXT,
	trimId TEXT,
	trim_name TEXT, 
	vehicle_damage_category TEXT, 
	wheel_system TEXT,
	wheel_system_display TEXT,
	wheelbase TEXT,
	width TEXT,
	year TEXT
	);
	
ALTER TABLE used_cars
	DROP COLUMN combine_fuel_economy,
	DROP COLUMN vehicle_damage_category,
	DROP COLUMN is_certified;